In [1]:
import numpy as np
from torch.utils.data import DataLoader
from torch import nn
import random
import math
import torch
from torch import nn
from torch import optim
from tensorboardX import SummaryWriter
from datetime import datetime
import time
import pygame
import load
from models import DynamicTopologyModel
import load_topology_dataset
from load_topology_dataset import MAX_CELL_COUNT, MIN_CELL_COUNT, IMAGE_SIZE
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#device="cpu"
EXPERIMENT=13
writer = SummaryWriter('runs/experiment_{}/'.format(EXPERIMENT))

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
cells =[(6, 0), (25,0)]
loads = [(0, 0)]
load.calculate_cell_load(cells, loads)

[(6, 0, 0.5857350800582242), (25, 0, 0.41426491994177583)]

In [3]:
0.2 * 32

6.4

In [4]:
def save_parameters(writer, model, batch_idx):
    for k, v in model.state_dict().items():
        shape = v.shape
        # Don't do this for single weights or biases
        if np.any(np.array(shape) > 1):
            mean = torch.mean(v)
            std_dev = torch.std(v)
            maximum = torch.max(v)
            minimum = torch.min(v)
            writer.add_scalars("{}_{} ".format(k, shape), {"mean": mean,
                                                                    "std_dev": std_dev,
                                                                    "max": maximum,
                                                                    "min": minimum}, batch_idx)
            writer.add_histogram("{}_{}".format(k, shape), v, batch_idx)
            
        else:
            writer.add_scalar("{}_{}".format(k, shape), v.data, batch_idx)

In [5]:
def test_parameters_update(last_parameters_np ,parameters_np):
    for last_param, param in zip(last_parameters_np, parameters_np):
        diff = param - last_param
        #print(last_parameters.max())
        print(diff.max())
        #print(not np.all(diff))


In [6]:
def print_example(reference_cell_input, reference_cell_present_input,
                neighbourhood_cell_rel_input, neighbourhood_cell_load_input, neighbourhood_cell_present_input,
                  reference_cell_target, reference_cell_present_target, neighbourhood_cell_rel_target,
                  neighbourhood_cell_present_target):
    print("reference_cell_input") 
    print(reference_cell_input)
    print("reference_cell_present_input") 
    print(reference_cell_present_input)
    print("neighbourhood_cell_rel_input") 
    print(neighbourhood_cell_rel_input)
    print("neighbourhood_cell_load_input") 
    print(neighbourhood_cell_load_input)
    print("neighbourhood_cell_present_input") 
    print(neighbourhood_cell_present_input)
    print("reference_cell_target") 
    print(reference_cell_target)
    print("reference_cell_present_target") 
    print(reference_cell_present_target)
    print("neighbourhood_cell_rel_target") 
    print(neighbourhood_cell_rel_target)
    print("neighbourhood_cell_present_target") 
    print(neighbourhood_cell_present_target)

In [7]:
# Define Model
if True:
    dynamic_topology_model = torch.load("model.pt")
else:
    dynamic_topology_model = DynamicTopologyModel(neighbourhood_hidden_size=32, neighbourhood_cell_count=2,
                     neighbourhood_output_size=16, lstm_hidden_size=64, lstm_layers=2, teacher_forcing_probability=0.5, device=device).to(device)


In [8]:
BATCH_SIZE = 32 
INPUT_SEQ_LEN = 3
TARGET_SEQ_LEN = 1
LEARNING_RATE = 1e-4
SAVE_VARIABLE_EVERY = 100
DATASET_WORKERS = 0
max_loss = 0.0

input_seq_len= torch.Tensor([INPUT_SEQ_LEN]).int()
target_seq_len= torch.Tensor([TARGET_SEQ_LEN]).int()

# Define Data.
cell_load_dataset = load_topology_dataset.LoadCellDataset(initial_cell_counts=(1, 2), initial_load_counts=(1,1),
                                    input_seq_len=INPUT_SEQ_LEN, target_seq_len=TARGET_SEQ_LEN,
                                                          network_mutate_prob=[0.3, 0.4
                                                                                                                    ])
dataloader = DataLoader(cell_load_dataset, batch_size=BATCH_SIZE,
                        shuffle=False, num_workers=DATASET_WORKERS)


parameters = dynamic_topology_model.parameters

# Define optimizer
optimizer = optim.Adam(parameters
                       , lr=LEARNING_RATE)
criterion = nn.MSELoss()
last_parameters_np = list(np.copy(param.cpu().detach().numpy()) for param in parameters)

# Train
start = datetime.now()
for batch_idx, data in enumerate(dataloader):
    optimizer.zero_grad()
    reference_cell_input =  data[0].to(device)
    reference_cell_present_input = data[1].to(device)
    neighbourhood_cell_rel_input = data[2].to(device)
    neighbourhood_cell_load_input = data[3].to(device)
    neighbourhood_cell_present_input = data[4].to(device)
    reference_cell_target = data[5].to(device)
    reference_cell_present_target = data[6].to(device)
    neighbourhood_cell_rel_target = data[7].to(device)
    neighbourhood_cell_present_target = data[8].to(device)
    
    
    decoder_output_seq = dynamic_topology_model.forward(input_seq_len, target_seq_len, reference_cell_input, reference_cell_present_input,
                neighbourhood_cell_rel_input, neighbourhood_cell_load_input, reference_cell_target, reference_cell_present_target, neighbourhood_cell_rel_target)
    
    loss = criterion(decoder_output_seq, reference_cell_target)
    loss.backward()
    optimizer.step()
    
    if loss > max_loss:
        print("max_loss")
        max_loss = loss
        print("loss: {}".format(loss))
        print("output: {}".format(decoder_output_seq))
        print("target: {}".format(reference_cell_target))
    if batch_idx == 0:
        parameters = dynamic_topology_model.parameters
        parameters_np = list(param.cpu().detach().numpy() for param in parameters)
        test_parameters_update(last_parameters_np, parameters_np)
        inputs =(input_seq_len, target_seq_len, reference_cell_input, reference_cell_present_input,
                neighbourhood_cell_rel_input, neighbourhood_cell_load_input, reference_cell_target, reference_cell_present_target, neighbourhood_cell_rel_target)
        writer.add_graph(dynamic_topology_model, inputs, True)
    if batch_idx % SAVE_VARIABLE_EVERY == 0:
        torch.save(dynamic_topology_model, "model.pt")
        #print_example(reference_cell_input, reference_cell_present_input,
        #            neighbourhood_cell_rel_input, neighbourhood_cell_load_input, neighbourhood_cell_present_input,
        #              reference_cell_target, reference_cell_present_target, neighbourhood_cell_rel_target,
        #              neighbourhood_cell_present_target)    
        end = datetime.now()
        print("{} Examples/sec".format((SAVE_VARIABLE_EVERY* BATCH_SIZE) / ((end - start).total_seconds()) ))
        start = datetime.now()
        print("loss: {}".format(loss))
        #print("output: {}".format(decoder_output_seq))
        #print("target: {}".format(reference_cell_target))
        writer.add_scalar("loss", loss, batch_idx)
        save_parameters(writer, dynamic_topology_model, batch_idx)


max_loss
loss: 0.36428922414779663
output: tensor([[[0.0854]],

        [[0.0846]],

        [[0.0868]],

        [[0.0851]],

        [[0.0855]],

        [[0.0875]],

        [[0.0846]],

        [[0.0864]],

        [[0.0846]],

        [[0.0853]],

        [[0.0855]],

        [[0.0846]],

        [[0.0854]],

        [[0.0851]],

        [[0.0854]],

        [[0.0854]],

        [[0.0846]],

        [[0.0853]],

        [[0.0853]],

        [[0.0857]],

        [[0.0853]],

        [[0.0846]],

        [[0.0846]],

        [[0.0861]],

        [[0.0851]],

        [[0.0852]],

        [[0.0870]],

        [[0.0846]],

        [[0.0865]],

        [[0.0846]],

        [[0.0854]],

        [[0.0846]]], grad_fn=<CopySlices>)
target: tensor([[[0.5428]],

        [[1.0000]],

        [[0.0000]],

        [[0.6717]],

        [[0.4914]],

        [[0.0000]],

        [[1.0000]],

        [[0.0000]],

        [[1.0000]],

        [[0.4519]],

        [[0.4499]],

        [[1.0000]],

   

/Users/nsgoodger/personal/dynamic_topology/models.py:197: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, target_seq_len.data.numpy()[0], 1), device=self.device
/Users/nsgoodger/personal/dynamic_topology/models.py:201: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for input_seq_idx in range(input_seq_len):
/Users/nsgoodger/personal/dynamic_topology/models.py:232: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in

max_loss
loss: 0.4065496027469635
output: tensor([[[0.0863]],

        [[0.0863]],

        [[0.0866]],

        [[0.0877]],

        [[0.0860]],

        [[0.0879]],

        [[0.0860]],

        [[0.0868]],

        [[0.0879]],

        [[0.0863]],

        [[0.0860]],

        [[0.0881]],

        [[0.0870]],

        [[0.0862]],

        [[0.0860]],

        [[0.0863]],

        [[0.0863]],

        [[0.0868]],

        [[0.0864]],

        [[0.0880]],

        [[0.0865]],

        [[0.0872]],

        [[0.0860]],

        [[0.0867]],

        [[0.0863]],

        [[0.0864]],

        [[0.0880]],

        [[0.0860]],

        [[0.0873]],

        [[0.0868]],

        [[0.0873]],

        [[0.0864]]], grad_fn=<CopySlices>)
target: tensor([[[1.0000]],

        [[1.0000]],

        [[0.4292]],

        [[0.0000]],

        [[1.0000]],

        [[0.0000]],

        [[1.0000]],

        [[0.4183]],

        [[0.0000]],

        [[1.0000]],

        [[1.0000]],

        [[0.0000]],

    

KeyboardInterrupt: 

In [28]:
(reference_cell_target <= 1.0).min().item()

1

In [14]:
def add_cell_if_not_exists(new_cell, cells):
    cell_already_exists = False

    for i, cell in enumerate(cells):
        if cell[0] == new_cell[0] and cell[1] == new_cell[1]:
            cell_already_exists = True
            break
    if not cell_already_exists:
        cells.append(new_cell)
    return cells

def remove_cell_if_exists(remove_cell, cells):
    for i, cell in enumerate(cells):
        if cell[0] == remove_cell[0] and cell[1] == remove_cell[1]:
            cells.pop(i)
            break
    return cells


In [ ]:
PIXELS = 640
LEFT = 1
RIGHT = 3
INPUT_SCREEN_COUNT = 3
TARGET_SCREEN_COUNT = 1
SCREEN_COUNT = INPUT_SCREEN_COUNT + TARGET_SCREEN_COUNT

PIXELS_PER_BLOCK = int(PIXELS / IMAGE_SIZE)
SCALE_ARR = np.ones((PIXELS_PER_BLOCK, PIXELS_PER_BLOCK, 1))

load_screen = np.zeros((IMAGE_SIZE, IMAGE_SIZE, 1))
#load_screen[1,12, 0] = 255
#load_screen[22,22, 0] = 255
loads = [(1, 12), (22, 22)]


screen = pygame.display.set_mode((PIXELS, PIXELS))
screens = []

screen_draw_idx = 0
last_pos = (0, 0)
color = (255, 128, 0)
radius = 10
block_screen = np.zeros((IMAGE_SIZE, IMAGE_SIZE, 3))
model_screen = np.zeros((IMAGE_SIZE, IMAGE_SIZE, 3), dtype=np.uint8)
frame = 0
cells_seq = [list() for i in range(SCREEN_COUNT)]
#cells_load_seq = [list() for i in range(SCREEN_COUNT)]
BATCH_SIZE=1
show_labels = True
input_seq_len= torch.Tensor([INPUT_SCREEN_COUNT]).int()
target_seq_len= torch.Tensor([TARGET_SCREEN_COUNT]).int()

load_cells_seq_input_0, load_cells_seq_target_0, loads = load_topology_dataset.LoadCellDataset.generate_inputs_and_targets(INPUT_SCREEN_COUNT, TARGET_SCREEN_COUNT,
                                            (1, 1), (2,2), (0.3, 0.4))

cells_load_seq = load_cells_seq_input_0 + load_cells_seq_target_0
#print(cells_load_seq)
for seq_idx in range(len(cells_load_seq)):
    for cell_idx in range(len(cells_load_seq[seq_idx])):
        cells_seq[seq_idx].append((cells_load_seq[seq_idx][cell_idx][0], cells_load_seq[seq_idx][cell_idx][1]))

print(loads)
for load_item in loads:
    load_screen[load_item[0], load_item[1], 0] = 255

    
block_img = np.kron(load_screen, SCALE_ARR)    
while True:
    
    ##############################
    # Use model to forecast future load
    ##############################
    load_cells_seq_input = cells_load_seq[:INPUT_SCREEN_COUNT]
    load_cells_seq_target = cells_load_seq[INPUT_SCREEN_COUNT:]
    
 
    model_target = [list() for i in range(TARGET_SCREEN_COUNT)]
    if screen_draw_idx < INPUT_SCREEN_COUNT:
        caption = "Input frame {}".format(screen_draw_idx)
    elif show_labels:
        caption = "Label frame {}".format(screen_draw_idx)
    else:
        caption = "Model frame {}".format(screen_draw_idx)
    pygame.display.set_caption(caption)
    for seq_idx  in range(TARGET_SCREEN_COUNT):
        for reference_cell in cells_seq[INPUT_SCREEN_COUNT + seq_idx]:
            #print(reference_cell)
            ref_x, ref_y = reference_cell[0], reference_cell[1]

            # Get inputs from state.
            (reference_cell_input,
             reference_cell_present_input,
             neighbourhood_cell_rel_input,
             neighbourhood_cell_load_input,
             neighbourhood_cell_present_input,
             reference_cell_target,
             reference_cell_present_target,
             neighbourhood_cell_rel_target,
             neighbourhood_cell_present_target,) = load_topology_dataset.LoadCellDataset.build_inputs_and_targets(INPUT_SCREEN_COUNT,
                                                                                                 TARGET_SCREEN_COUNT,
                                                                                                 ref_x, ref_y,
                                                                                                 load_cells_seq_input,
                                                                                                 load_cells_seq_target)
            # Infer output from model.  Add batch dimension to each input since dataloader is not used here.
            decoder_output_seq = dynamic_topology_model.forward(input_seq_len, target_seq_len,
                                                                reference_cell_input.unsqueeze(0),
                                                                reference_cell_present_input.unsqueeze(0),
                                                                neighbourhood_cell_rel_input.unsqueeze(0),
                                                                neighbourhood_cell_load_input.unsqueeze(0),
                                                                reference_cell_target.unsqueeze(0),
                                                                reference_cell_present_target.unsqueeze(0),
                                                                neighbourhood_cell_rel_target.unsqueeze(0))

            model_target[seq_idx].append((ref_x, ref_y, decoder_output_seq.detach().numpy()[0][seq_idx][0]))    
    ################################
    # DISPLAY
    #################################
    screen_draw = pygame.Surface((PIXELS, PIXELS))
    
    #print(cells_seq)
    cells = cells_seq[screen_draw_idx]
    cell_loads = cells_load_seq[screen_draw_idx]

    if (screen_draw_idx < INPUT_SCREEN_COUNT) or (show_labels and screen_draw_idx >= INPUT_SCREEN_COUNT):
        for cell in cell_loads:
            color = cell[2] * 255
            if color > 255:
                color = 255
            if color < 0:
                color = 0
            pygame.draw.rect(
            screen_draw,
            (color, 50, 0),
            (
                cell[0] * PIXELS_PER_BLOCK,
                cell[1] * PIXELS_PER_BLOCK,
                PIXELS_PER_BLOCK,
                PIXELS_PER_BLOCK,),
            )
    else:
        model_loads = model_target[screen_draw_idx - INPUT_SCREEN_COUNT]
        for cell in model_loads:
            #color = (cell[2] * 2024) - 512
            color = (cell[2] * 255)
            if color > 255:
                color = 255
            if color < 0:
                color = 0
            pygame.draw.rect(
            screen_draw,
            (color, 50, 0),
            (
                cell[0] * PIXELS_PER_BLOCK,
                cell[1] * PIXELS_PER_BLOCK,
                PIXELS_PER_BLOCK,
                PIXELS_PER_BLOCK,),
            )

    e = pygame.event.poll()


    if e.type == pygame.QUIT:
        raise StopIteration
    if e.type == pygame.MOUSEBUTTONDOWN:
        leftclick, middleclick, rightclick = pygame.mouse.get_pressed()
        x, y = e.pos
        x_cell= int(x / PIXELS_PER_BLOCK)
        y_cell = int(y / PIXELS_PER_BLOCK)
        if leftclick and (len(cells) < load_topology_dataset.MAX_CELL_COUNT):
            cells = add_cell_if_not_exists((x_cell, y_cell), cells)
        elif rightclick and (len(cells) > load_topology_dataset.MIN_CELL_COUNT):
            cells = remove_cell_if_exists((x_cell, y_cell), cells)            
        # Update cells
        cells_seq[screen_draw_idx] = cells

        
        # Update all cell loads
        for i, cells in enumerate(cells_seq):
            cells_load_seq[i] = load.calculate_cell_load(cells, loads)
        print(cells_load_seq)   
    if e.type == pygame.KEYDOWN:
        if e.key == pygame.K_SPACE:
            if show_labels:
                show_labels = False
            else:
                show_labels = True
                print(reference_cell_target)
                print(neighbourhood_cell_rel_target)
                print(model_target[screen_draw_idx - INPUT_SCREEN_COUNT])
                print(load_cells_seq_target[screen_draw_idx - INPUT_SCREEN_COUNT])
        if e.key ==  pygame.K_LEFT:
            if screen_draw_idx > 0:
                screen_draw_idx -= 1
        if e.key ==  pygame.K_RIGHT:
            if screen_draw_idx < SCREEN_COUNT - 1:
                screen_draw_idx += 1
    pygame.display.flip()
    target_screen = pygame.surfarray.array3d(screen_draw)
    display_img = block_img + target_screen
    new_surf = pygame.pixelcopy.make_surface(display_img.astype(np.uint8))
    screen.blit(new_surf, (0, 0))


[(22, 10)]
[[(25, 0, 0.49439061703212644), (29, 6, 0.5056093829678735)], [(25, 0, 0.49439061703212644), (29, 6, 0.5056093829678735)], [(25, 0, 0.49439061703212644), (29, 6, 0.5056093829678735)], [(29, 6, 0.4951310861423221), (23, 5, 0.5048689138576778)]]
tensor([[0.5049]])
tensor([[[0.8125, 0.9688],
         [0.0000, 0.0000]]])
[(29, 6, 0.508934), (23, 5, 0.43338147)]
[(29, 6, 0.4951310861423221), (23, 5, 0.5048689138576778)]
tensor([[0.5049]])
tensor([[[0.8125, 0.9688],
         [0.0000, 0.0000]]])
[(29, 6, 0.508934), (23, 5, 0.43338147)]
[(29, 6, 0.4951310861423221), (23, 5, 0.5048689138576778)]
tensor([[0.5049]])
tensor([[[0.8125, 0.9688],
         [0.0000, 0.0000]]])
[(29, 6, 0.508934), (23, 5, 0.43338147)]
[(29, 6, 0.4951310861423221), (23, 5, 0.5048689138576778)]
[[(25, 0, 0.49439061703212644), (29, 6, 0.5056093829678735)], [(25, 0, 0.49439061703212644), (29, 6, 0.5056093829678735)], [(25, 0, 0.49439061703212644), (29, 6, 0.5056093829678735)], [(29, 6, 1.0)]]
[[(25, 0, 0.49439061

In [ ]:
neighbourhood_cell_rel_input

In [ ]:
model_target

In [ ]:
for seq_idx  in range(TARGET_SCREEN_COUNT):
    print(seq_idx)
    model_target[seq_idx].append((ref_x, ref_y, decoder_output_seq.detach().numpy()[0][seq_idx][0]))

In [ ]:

cell_load_dataset = load_topology_dataset.LoadCellDataset(initial_cell_counts=(2, 5), initial_load_counts=(2,24),
                                    input_seq_len=INPUT_SEQ_LEN, target_seq_len=TARGET_SEQ_LEN, network_mutate_prob=[0.2, 0.2])



In [ ]:
decoder_output.detach().numpy()[seq_idx][0]

In [ ]:
len(cells_load_seq[0])

In [42]:
cells_seq = [(cell_load[0], cell_load[1]) for cell_load in cell_load for cell_load_seq in cells_load_seq]

SyntaxError: invalid syntax (<ipython-input-42-8e3eb257a1ca>, line 1)

In [41]:
decoder_output_seq

tensor([[[0.1995],
         [0.2303],
         [0.2037]]], grad_fn=<CopySlices>)

In [11]:
load_cells_seq_input_0, load_cells_seq_target_0, loads = load_topology_dataset.LoadCellDataset.generate_inputs_and_targets(INPUT_SCREEN_COUNT, TARGET_SCREEN_COUNT,
                                            (1, 1), (2,2), (0.3, 0.4))

remove_input_cell


In [9]:
math.sqrt(2)

1.4142135623730951

In [11]:
load = math.sqrt(2) - np.power( 1.23743687, 2)

In [12]:
load

-0.1170364448623018

In [13]:
math.square(1.44)

AttributeError: module 'math' has no attribute 'square'